### ISSUE TITLE
Segmentation Fault running Example1 from KISS_SDL 0.10.2

### ISSUE THREAD

**Issue by AVividLight** [actsl/kiss_sdl#1]
Hello!

I'm trying to build the first example, but it's throwing a segmentation fault (`Segmentation fault: 11`) when I run it. Everything does compile (albeit with lots of depreciation warnings) and link fine; I haven't really looked into the code to see if I can figure out why it's not working yet, I wanted to post here in case I'm already doing something wrong. I don't have a lot of experience with linking C to C++ code, so that could be the root of my problem. Also, the Makefile was not able to find my installation of SDL2, so I made a small CMakeLists for the project. I think it's unlikely that this would cause an issue, but it certainly could, as I'm pretty new to using CMake.

Bellow is the OS-generated [Mac OSX 10.11.5 Beta (15F31a)] crash log, and my entire test-project. Please let me know if there's any more information I can provide to help fix this.

[Problem Report.txt](https://github.com/actsl/kiss_sdl/files/265263/Problem.Report.txt)
[Test_KISS.zip](https://github.com/actsl/kiss_sdl/files/265266/Test_KISS.zip)

Thank you!
Michael

**Comment by actsl** [comment]
Please see the next release i will make today or tomorrow, to improve compiling in Windows. This is all i can do, i cannot guarantee that it works with any libraries CMake may choose, this is also why i didn't use CMake.

**Comment by AVividLight** [comment]
If it makes any difference, I'm using an Apple Mac, but I can test this with Windows or Debian/Linux, if it'd help. SDL, SDL_TTF, and SDL_Image all work just fine in my other projects (also using CMake), so I think the issue is either in how I wrote the CMakeLists or how I'm accessing the pure C KISS_SDL header from C++ (this is my first time trying to use pure C in C++, so I think this may be the culprit), barring an actual bug in the KISS_SDL source.

Thanks for getting back to me, though! I'll look for the update, and report back once I've had a chance to test it.

**Comment by actsl** [comment]
The version 0.10.4 is now up. I described in README precisely how i compiled it, this is how it should work with MinGW.

A bug in kiss_sdl is highly unlikely, because it works in Linux 64 bit, with Windows 32 bit MinGW and Windows 32 bit Visual Studio.

The kiss_sdl functions can be called from C++, as they are declared by C++ conventions when __cplusplus is defined, this is the standard way of declaring C functions for C++, and should not be problem. The SDL2 functions are also written in C and declared the same way.

I have not targeted Macintosh, so i'm not sure what the linker and compiler flags should be for it. Unfortunately i cannot reproduce the issue, because i don't have Macintosh. I can only reproduce an issue in 64 bit Linux or 32 bit Windows, when i know exactly what libraries were used, and what the linker and compiler flags were.

What can i advise, make sure that you have proper SDL2 libraries installed, it is tested with SDL2-2.0.4, SDL2_image-2.0.1 and SDL2_ttf-2.0.14, thus it may not work with earlier versions. gcc and SDL2 libraries also have to be of the same number of bits, either 32 or 64, and 64 can be used only when OS is 64 bit, beyond doubt it doesn't work otherwise. When compiling with 32 bit libraries in 64 bit OS, there should be -march=i686 both in linker flags and compiler flags, as gcc may default to the architecture of the machine. When all these things are right then it should work.

**Comment by actsl** [comment]
Looking at the cmake log, you have a 64 bit operating system. Not sure whether your SDL2 libraries are also 64 bit, it likely works the best when they were. Your compiler is Apple Clang, not gcc. It is capable of compiling c. This may be one problem though, not sure whether it works correctly when compiled with Apple Clang. The code is c89, that is the simplest, yet Apple Clang may not compile it exactly the same way as gcc. You may try to compile it with gcc, not sure though that this is a problem at all. Visual Studio compiles it with no problem, and it is not gcc.

**Comment by actsl** [comment]
I tried it, at least with Clang in Linux it compiles with no problems, and completely works also.

**Comment by AVividLight** [comment]
Thank you for going to all this effort to help me understand what's wrong!

I have been using SDL2 in other projects for a while, so I believe I have the correct libraries for my system. I've heard that Clang with LLVM can impersonate GCC in some way (or at least understands commands for it), and a lot of OSX's core is written in pure C, so I'm sure the Xcode Clang/LLVM compiler is fully capable.

Did you write your own CMakeLists, or use mine? If you wrote one yourself, may I try it? I'm pretty new to CMake, so like I've said, it's likely I did something incorrectly. If you have, however, used the archive I posted above, I'll seek help on StackOverflow for an issue specific to Mac. I'm also going to try building the examples on Linux myself, I'll write again to say how it goes.

Thanks, I really appreciate your support, and the KISS library itself, you're doing a great job!
Michael

**Comment by actsl** [comment]
With your CMakeLists.txt, FindSDL2.cmake, FindSDL2_image.cmake and FindSDL2_ttf.cmake it compiles fine in Linux and runs fine. Below is a simplified cmake test project with your CMakeLists.txt, that did it.
[cmakekisssdl.zip](https://github.com/actsl/kiss_sdl/files/267391/cmakekisssdl.zip)

**Comment by actsl** [comment]
Thank you for your appreciation :)

I didn't add your main.cpp, but even when i did that, exactly as you did, it still compiles and runs fine.

I guess i know what the problem is. The only difference between my CMakeLists.txt and your CMakeLists.txt is that i put everything in one directory, while you as much as i see have sources in ./src, and executable in ./build/bin.

It crashed when calling TTF_FontHeight(), as the problem report seems to show, that is the font was likely not loaded.

When the executable is in a different directory than the resources (fonts and images), then a macro has to be added to the compiler's command line (compiler flags), that provides the path of the resources, this was not done.

So this may be the cause, and nothing else is wrong.

[cmakekisssdl2.zip](https://github.com/actsl/kiss_sdl/files/267423/cmakekisssdl2.zip)

**Comment by actsl** [comment]
For example if your binary is in  ./build/bin  and resources are in  ./src  then it would be  -DRESDIR=\"../../src/\" .

**Comment by AVividLight** [comment]
Thank you very much, the issue was the missing font (specifically, that I didn't specify the resource directory)! You've been so helpful, I really appreciate your support, even in light of my ignorance. I will continue using your fantastic library, and contribute in any way I can!

Thanks again!
Michael
