### ISSUE TITLE
Android builds but crashes

### ISSUE THREAD

**Issue by gwald** [actsl/kiss_sdl#11]
Hi, 
Good and simple little GUI kit!
I'm guessing it's not compatible with mobile?
Anyone got it working?

I got kiss_sdl built and example 1 working on linux and also built on NDK but when running it I get:

> adb logcat com.example.hellojni:V hellojni:V   SDL:V SDL2:V org.libsdl.app.SDLActivity:V  com.example.hellojni/.HelloJni:V   *:S
> 
> V/SDL     ( 4092): Device: phone
> V/SDL     ( 4092): Model: phone
> V/SDL     ( 4092): onCreate(): null
> V/SDL     ( 4092): onResume()
> V/SDL     ( 4092): surfaceCreated()
> V/SDL     ( 4092): surfaceChanged()
> V/SDL     ( 4092): pixel format RGB_565
> V/SDL     ( 4092): Window size: 545x295
> I/SDL     ( 4092): SDL_Android_Init()
> I/SDL     ( 4092): SDL_Android_Init() finished!
> V/SDL     ( 4092): onWindowFocusChanged(): true
> V/SDL     ( 4092): onWindowFocusChanged(): false
> V/SDL     ( 4092): onPause()
> V/SDL     ( 4092): nativePause()
> V/SDL     ( 4092): surfaceDestroyed()
> V/SDL     ( 4092): surfaceCreated()
> V/SDL     ( 4092): onDestroy()

I'm a noob with Android.. so maybe I'm missing how to debug properly.
All the images are in the asset folder and accessible.
Any tips?
Cheers

**Comment by gwald** [comment]
Disregard works fine!
Android didn't handle the fprintf stderr.
It was a missing texture.
Thanks for the GUI, it's pretty cool!

Don't know how to close this issue :/

**Comment by actsl** [comment]
Sent: Friday, October 07, 2016 at 1:32 AM

**Comment by actsl** [comment]
Many thanks for building it for Android :)

I have never tried to build it for Android. I can test it though, different from a pull request here that requires a high DPI monitor, which i don't have. I have Android studio installed and an Android emulator, but i don't have an Android smartphone or tablet.

It would be good if you let others know how to build it for Android, but not exactly sure what is the best way to do that. You can make a pull request, i though don't commit any pull requests to the code,  i add changes to the code, and if the pull request is useful, i add its author to the credits. Or maybe better is to describe how you did it in the thread about kiss_sdl in the SDL development forum http://forums.libsdl.org/viewtopic.php?t=11772&sid=22ae2609397e467fcb2a61a158df5509 , because it is not only about changes in code or such, if there even were any.

Again, many thanks.

**Comment by actsl** [comment]
A version for Android is now in the kiss_sdl branch android, with full instructions how to build it for Android. The source code was all taken from the kiss_sdl testing branch. It worked fine for me, hope it also works for anyone else. I wrote about it also in the SDL development forum https://discourse.libsdl.org/t/kiss-sdl-simple-universal-gui-widget-toolkit-for-sdl/21675 .
