### ISSUE TITLE
Have kiss_sdl use an existing SDL_Renderer?

### ISSUE THREAD

**Issue by midn1** [actsl/kiss_sdl#15]
It seems `kiss_init` creates an entirely new `SDL_Window` along with it's `SDL_Renderer` and all that.  
But how would I use this for e.g a game UI where they it should be on the same window?

**Comment by actsl** [comment]
Create window with kiss_init()?

This toolkit is simple, all is made so that it were as simple as possible, but still generic. Maybe there would be a need to use a renderer from another window, all i can say is that in any more complicated cases the kiss_sdl code should be changed. Nothing to do, this is the price of making it simple, but being simple is worth of it.

Thank you for pointing it out, i will leave this issue open for a few days, then close, when there is no need to do otherwise, because this feature was not intended by design.
