### ISSUE TITLE
Duplicate definitions in kiss_sdl.h

### ISSUE THREAD

**Issue by AVividLight** [actsl/kiss_sdl#2]
Hello!

Sorry to raise another issue here, but I'm having trouble using KISS_SDL with C++. Specifically, when linking the example code from page 4 of the manual, several duplicate symbol linker errors pop up. I asked about this on StackOverflow, and the answer I got seemed to suggest that the header does actually contain duplicate variable definitions. As a preliminary test, I commented out a few of the duplicate variables from kiss_sdl.h, and several of the linker errors were solved. I'm going to do some digging to see if I can do something about this without modifying the library, but I wanted to bring your attention to it, in case the header or manual needs to be modified.

For reference, the StackOverflow question is [here](http://stackoverflow.com/questions/37350359/duplicate-symbols-when-mixing-c-and-c), please see it for specifics.

Thank you!
Michael

**Comment by AVividLight** [comment]
For example, in the kiss_sdl.h there is the following block of definitions (starting at line 242):

```
SDL_Color kiss_white, kiss_black, kiss_green, kiss_blue, kiss_lightblue;
kiss_font kiss_textfont, kiss_buttonfont;
kiss_image kiss_normal, kiss_prelight, kiss_active, kiss_bar, kiss_up, kiss_down, kiss_left, kiss_right, kiss_vslider, kiss_hslider, kiss_selected, kiss_unselected;
double kiss_spacing;
int kiss_textfont_size, kiss_buttonfont_size;
int kiss_click_interval, kiss_progress_interval;
int kiss_slider_padding;
int kiss_border, kiss_edge;
int kiss_screen_width, kiss_screen_height;
```

Then, in kiss_draw.c, the variables are defined again (starting at line 27):

```
int kiss_textfont_size = 15;
int kiss_buttonfont_size = 12;
int kiss_click_interval = 140;
int kiss_progress_interval = 50;
int kiss_slider_padding = 2;
int kiss_edge = 2;
int kiss_border = 6;
double kiss_spacing = 0.5;
SDL_Color kiss_white = {255, 255, 255, 255};
SDL_Color kiss_black = {0, 0, 0, 255};
SDL_Color kiss_green = {0, 150, 0, 255};
SDL_Color kiss_blue = {0, 0, 255, 255};
SDL_Color kiss_lightblue = {200, 225, 255, 255};
```

Of course, this is your project, and you certainly know a lot more about how it works than I do. Please correct me if I'm misunderstanding how it works, I'd love to have a better grasp on it!

**Comment by AVividLight** [comment]
Changing the bit in kiss_sdl.h to the following fixes the linker errors, and I am now able to build and link the project!

At line 242,

```
extern SDL_Color kiss_white, kiss_black, kiss_green, kiss_blue, kiss_lightblue;
kiss_font kiss_textfont, kiss_buttonfont;
kiss_image kiss_normal, kiss_prelight, kiss_active, kiss_bar, kiss_up, kiss_down, kiss_left, kiss_right, kiss_vslider, kiss_hslider, kiss_selected, kiss_unselected;
extern double kiss_spacing;
extern int kiss_textfont_size, kiss_buttonfont_size;
extern int kiss_click_interval, kiss_progress_interval;
extern int kiss_slider_padding;
extern int kiss_border, kiss_edge;
int kiss_screen_width, kiss_screen_height;
```

I have created a pull request, please review it [here](https://github.com/actsl/kiss_sdl/pull/3).

**Comment by actsl** [comment]
This double definition is perfectly OK in C, but not in C++.

But most importantly, this construct

```
#ifdef __cplusplus
extern "C" {
#endif
```

works only for functions, and does not work for variables. This construct makes the compiled file linkable both by C and C++ conventions, when it is compiled by a C++ compiler, thus the functions in it can be called both from C and C++ code. This construct therefore appeared to be useless for this widget toolkit.

This widget toolkit can either be compiled with only a C compiler (every file of it, and linking) or only a C++ compiler. C compilers are gcc and clang, but they act as C compilers only when the files extension is c, otherwise they act as C++ compilers. C++ compilers are g++ and clang++ , and they also act as C++ compilers when the files extension is c.

Unfortunately i couldn't use your pull request, because i wanted it to still work in C, but also making it to compile as C++ required some additional changes. I made the new version 0.10.6, that is in GitHub now, that enables to compile a project entirely in C++. With that you should be able to use this widget toolkit in a C++ application. But thank you, this helps others who also want to use it in a C++ code.

**Comment by AVividLight** [comment]
Thank you very much for the support, I'm just glad that KISS keeps getting better and better!
